-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 11:36:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eatdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eatdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eatdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `eatdb` ;

-- -----------------------------------------------------
-- Table `eatdb`.`Restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eatdb`.`Restaurants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `description` TEXT NULL,
  `cuisine` VARCHAR(100) NOT NULL,
  `website` VARCHAR(45) NULL,
  `img1` VARCHAR(100) NULL,
  `img2` VARCHAR(100) NULL,
  `img3` VARCHAR(100) NULL,
  `priceRange` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eatdb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eatdb`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(15) NOT NULL,
  `lastName` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `mobile` VARCHAR(15) NOT NULL,
  `password` VARCHAR(75) NOT NULL COMMENT 'SHA256 of password',
  `img` VARCHAR(45) NULL,
  `dateCreated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eatdb`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eatdb`.`Branch` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restID` INT UNSIGNED NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `contactNumber` VARCHAR(15) NOT NULL,
  `openingHrs` VARCHAR(100) NULL,
  `lat` DECIMAL(8,5) NULL,
  `long` DECIMAL(8,5) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `restID`
    FOREIGN KEY (`restID`)
    REFERENCES `eatdb`.`Restaurants` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eatdb`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eatdb`.`Reviews` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userID` INT UNSIGNED NOT NULL,
  `restID` INT UNSIGNED NOT NULL,
  `reviewTxt` TEXT NOT NULL,
  `score` INT UNSIGNED NOT NULL DEFAULT 3,
  `dateCreated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `singleReview_idx` (`userID` ASC, `restID` ASC) COMMENT 'To ensure each user can only submit 1 review per restaurant',
  CONSTRAINT `userFK`
    FOREIGN KEY (`userID`)
    REFERENCES `eatdb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `restFK`
    FOREIGN KEY (`restID`)
    REFERENCES `eatdb`.`Restaurants` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
